<?php

/**
 * @file
 * Contains tmgmt_ckeditor.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\editor\Entity\Editor;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function tmgmt_ckeditor_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the tmgmt_ckeditor module.
    case 'help.page.tmgmt_ckeditor':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('TMGT segments plugin for CKEditor') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_ckeditor_css_alter().
 *
 * @param array $css
 * @param \Drupal\editor\Entity\Editor $editor
 */
function tmgmt_ckeditor_ckeditor_css_alter(array &$css, Editor $editor) {
  $css[] = drupal_get_path('module', 'tmgmt_ckeditor') . '/js/plugins/segments/css/segments.css';
  $css[] = drupal_get_path('module', 'tmgmt_ckeditor') . '/js/plugins/tags/css/tags.css';
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function tmgmt_ckeditor_form_tmgmt_job_item_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'tmgmt_ckeditor/segments_content';

  /** @var \Drupal\tmgmt\JobItemInterface $job_item */
  $job_item = $form_state->getFormObject()->getEntity();
  $form['#attached']['drupalSettings']['sourceLanguage'] = $job_item->getJob()->getSourceLangcode();
  $form['#attached']['drupalSettings']['targetLanguage'] = $job_item->getJob()->getTargetLangcode();
}
