<?php

/**
 * @file
 * Contains tmgmt_ckeditor.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\editor\Entity\Editor;
use Drupal\Core\Form\FormStateInterface;
use Drupal\tmgmt\JobItemInterface;

/**
 * Implements hook_help().
 */
function tmgmt_ckeditor_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the tmgmt_ckeditor module.
    case 'help.page.tmgmt_ckeditor':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('TMGT segments plugin for CKEditor') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_ckeditor_css_alter().
 *
 * @param array $css
 * @param \Drupal\editor\Entity\Editor $editor
 */
function tmgmt_ckeditor_ckeditor_css_alter(array &$css, Editor $editor) {
  $css[] = drupal_get_path('module', 'tmgmt_ckeditor') . '/js/plugins/segments/css/segments.css';
  $css[] = drupal_get_path('module', 'tmgmt_ckeditor') . '/js/plugins/tags/css/tags.css';
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function tmgmt_ckeditor_form_tmgmt_job_item_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'tmgmt_ckeditor/segments_content';

  /** @var \Drupal\tmgmt\JobItemInterface $job_item */
  $job_item = $form_state->getFormObject()->getEntity();
  $form['#attached']['drupalSettings']['sourceLanguage'] = $job_item->getJob()->getSourceLangcode();
  $form['#attached']['drupalSettings']['targetLanguage'] = $job_item->getJob()->getTargetLangcode();
}

/**
 * Implements hook_tmgmt_data_item_text_output_alter().
 */
function tmgmt_ckeditor_tmgmt_data_item_text_output_alter(&$text, $data_item, JobItemInterface $job_item) {
  if (preg_match_all('/(<([^\btmgmt\b]+[^\s]+)[^>]+?>)([^>]+?[^\/][^>]+>)/', $text, $matches)) {

    // Go through each HTML-tag match found.
    for ($i = 0, $max = count($matches[0]); $i < $max; $i++) {
      $unmasked_text = $matches[0][$i];

      // Mask opening HTML-tags for b-tags.
      if ($matches[2][$i] == 'b') {
        $unmasked_text = str_replace($matches[1][$i], '<tmgmt-tag element="' . $matches[2][$i] . '" raw="' . htmlspecialchars($matches[1][$i]) . '">', $unmasked_text);
      }
      // Mask HTML-tags for img-tag.
      elseif ($matches[2][$i] == 'img') {
        $unmasked_text = str_replace($matches[1][$i], '<tmgmt-tag element="' . $matches[2][$i] . '" raw="' . htmlspecialchars($matches[1][$i]) . '" />', $unmasked_text);
      }
      // Mask closing tag.
      if ($matches[4][$i] == '</' . $matches[2][$i] . '>') {
        $unmasked_text = str_replace('</' . $matches[2][$i] . '>', '</tmgmt-tag>', $unmasked_text);
      }

      // Mask each HTML-tag one by one.
      $text = str_replace($matches[0][$i], $unmasked_text, $text);
    }
  }
}

/**
 * Implements hook_tmgmt_data_item_text_input_alter().
 */
function tmgmt_ckeditor_tmgmt_data_item_text_input_alter(&$text, $data_item, JobItemInterface $job_item) {
  if (preg_match_all('/(<\btmgmt-tag\b[^"]+\"([\w]+)[^\braw\b]+[^"]+\"([^>]+)\"\s?\/?>?)[^<]+(<\/[^<]+)/', $text, $matches)) {

    // Go through each tmgmt-tag match found.
    for ($i = 0, $max = count($matches[0]); $i < $max; $i++) {
      $masked_text = $matches[0][$i];

      // Unmask opening tmgmt-tags for b-tags.
      if ($matches[2][$i] == 'b') {
        $masked_text = str_replace($matches[1][$i], htmlspecialchars_decode($matches[3][$i]), $masked_text);
      }
      // Unmask tmgmt-tags for img-tag.
      elseif ($matches[2][$i] == 'img') {
        $masked_text = str_replace($matches[1][$i] . '>', htmlspecialchars_decode($matches[3][$i]), $masked_text);
      }
      // Unmask closing tag.
      if ($matches[4][$i] == '</tmgmt-tag>') {
        $masked_text = str_replace('tmgmt-tag', $matches[2][$i], $masked_text);
      }

      // Unmask each tmgmt-tag one by one.
      $text = str_replace($matches[0][$i], $masked_text, $text);
    }
  }
}
