<?php

/**
 * @file
 * Contains tmgmt_ckeditor.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function tmgmt_ckeditor_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the tmgmt_ckeditor module.
    case 'help.page.tmgmt_ckeditor':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('TMGT segments plugin for CKEditor') . '</p>';
      return $output;

    default:
  }
}
