<?php

/**
 * @file
 * Contains tmgmt_ckeditor_test.module.
 */

use Drupal\tmgmt\JobItemInterface;

/**
 * Implements hook_tmgmt_data_item_text_output_alter().
 */
function tmgmt_ckeditor_test_tmgmt_data_item_text_output_alter(&$text, $data_item, JobItemInterface $job_item) {
  $text = str_replace('First', 'Second', $text);
}

/**
 * Implements hook_tmgmt_data_item_text_input_alter().
 */
function tmgmt_ckeditor_test_tmgmt_data_item_text_input_alter(&$text, $data_item, JobItemInterface $job_item) {
  $text = str_replace('Second', 'First', $text);
}
